[tool.ruff]
line-length = 100
target-version = "py312"
select = ["E", "F", "I", "B"]
exclude = ["venv", ".venv", "build", "dist", ".git"]

[tool.ruff.format]
quote-style = "preserve"

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
disallow_untyped_defs = false
exclude = ["tests/"]

[tool.bandit]
skips = ["B101"]
exclude_dirs = ["tests", "venv", ".venv", ".git", "build", "dist"]
