[tool.ruff]
line-length = 100
target-version = "py312"
exclude = ["venv", ".venv", "build", "dist", ".git", "qc", "tools"]

[tool.ruff.lint]
select = ["E", "F", "I", "B"]
ignore = [
  "E402",
  "E501",
  "B905",
]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["F401"]
