version: '3.8'
services:
  otel-collector:
    image: otel/opentelemetry-collector:0.102.1
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8888:8888"   # zPages
    environment:
      - LOG_LEVEL=info
