name: Lint / Types / Security
on:
  push:
  pull_request:
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy bandit pip-audit astor
      - name: Ruff (E9, F821, B008 only; ignore E402/B905)
        run: |
          ruff check . --config qc/ruff.toml --output-format=concise
      - name: Mypy (loose)
        run: |
          mypy . --config-file qc/mypy.ini
      - name: Bandit (non-blocking)
        continue-on-error: true
        run: |
          bandit -r . -c qc/bandit.yaml || true
      - name: pip-audit (non-blocking; ignore ecdsa GHSA)
        continue-on-error: true
        run: |
          if [ -f requirements.txt ]; then
            pip-audit -r requirements.txt --ignore-vuln GHSA-wj6h-64fc-37mp || true
          else
            echo "No requirements.txt found; skipping pip-audit"
          fi