---
name: CI
'on':
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  lint_type_security:
    name: Lint / Types / Security
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/idsideAI_Complete_PyCharm_Ready }
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install deps & tools
        run: |
          pip install --prefer-binary --no-input -r requirements.txt
          pip install --upgrade ruff black mypy bandit defusedxml
          pip install -U types-requests types-PyYAML types-python-dateutil types-redis types-setuptools

      # Auto-fix trivial style so checks won’t fail on formatting
      - name: Black (autofix)
        run: black .
      - name: Ruff (autofix)
        run: ruff check . --fix

      # Enforce
      - name: Black (check)
        run: black --check .
      - name: Ruff (check)
        run: ruff check .

      - name: Mypy (types)
        run: |
          mypy --install-types --non-interactive --config-file mypy.ini || true
          mypy --config-file mypy.ini

      - name: Bandit (security low/low)
        run: bandit -c bandit.yaml -r idsideAI_Complete_PyCharm_Ready --severity-level low --confidence-level low
