name: CI
on: [push, pull_request]

jobs:
  lint-type-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt ruff black mypy bandit defusedxml

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}/idsideAI_Complete_PyCharm_Ready" >> $GITHUB_ENV

      - name: Black (format check)
        run: black --check .

      - name: Ruff (lint)
        run: ruff check .

      - name: Mypy (types)
        run: mypy --config-file mypy.ini

      - name: Bandit (security low/low)
        run: bandit -c bandit.yaml -r idsideAI_Complete_PyCharm_Ready --severity-level low --confidence-level low
