name: Lint / Types / Security

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  python-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install tools & deps
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy bandit pip-audit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Ruff (lint)
        run: ruff check .

      - name: Mypy (types)
        run: |
          mypy --install-types --non-interactive || true
          mypy .

      - name: Bandit (security)
        run: bandit -r . -x tests

      - name: pip-audit (vulns)
        run: pip-audit --strict
